name: Docker Image
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Testing Secrets
      run: |
        echo "MONGO USER: $MONGO_USER"
        echo "$MONGO_USER"
      env:
        MONGO_USER: ${{ secrets.MONGO_USER }}

    - name: Run Python script
      run: python test.py
