name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - run: |
          Get-ChildItem Env: | Sort Name
      - name: Checkout code
        uses: actions/checkout@v2
      - run: python test.py
