name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  integration-tests:
    permissions:
      id-token: write # Important for at least docker gha cache
      contents: read

    name: "Run integration tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: docker/bake-action@master
        with:
          push: false
          load: true
          set: |
              *.cache-from=type=gha
              *.cache-to=type=gha,mode=max
          files: docker-compose.yml
