name: Docker Image
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: fails
        run: exit 1

  notification:
    runs-on: ubuntu-latest

    needs: build
    if: always()

    steps:
      - name: Echo debug
        run: |
          echo ${{ needs.build.result }}

      - name: Slack Notify Failure
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: echo "Failure"

      - name: Slack Notify Success
        if: !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
        run: echo "Success"
