name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: mkdir -p bin/test/ && echo "test artifact" > bin/test/test-artifact.txt

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: test-artifacts
          path: 'bin/test/*.txt'

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4.1.4
        with:
          name: test-artifacts
          path: build

      - run: cd ~ && pwd
