name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "test_value=123" >> $GITHUB_ENV
      - run: echo $test_value
      - run: echo {{ env.test_value }}
