name: Continuous Delivery

on:
  workflow_dispatch:
    inputs:
      build_version:
        description : 'Build Version'
        required: true
      abc:
        type: boolean
      xyz:
        type: boolean
  
jobs:
  getting_app_name:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        id: list_creation
        run: |
          declare -a names=()
          for option in abc xyz; do
            echo "option: $option"
            value=$(echo '${{ toJson(github.event.inputs) }}' | jq -r ".$option")
            echo "value: $value"
            if [[ "$value" == "true" ]]; then
              deployment_names+=("$option")
            fi
          done
          echo "names: ${deployment_names[@]}"
      