name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: >- 
            curl -X POST -v --location "www.example.com/example"
            -H "Authorization: Api-Token anAPiToken"
            -H "Content-Type: application/json; charset=utf-8"
            -d '{   "entitySelector": "entityId(SERVICE-8E3722AC3F76B09D)",\n
                    "eventType": "CUSTOM_DEPLOYMENT",\n
                    "title": "New Deployment Triggered",\n  
                    "properties": { \n
                        "RemediationUrl": "www.example.com/example"\n
                    }\n
                }'
