name: Docker Image
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: fails
        run: exit 1

  notification:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Echo debug
        run: |
          echo ${{ needs.build.outputs.status }}
          echo ${{ needs.build.outputs.result }}
          echo ${{ needs.build.result }}

      - name: Slack Notify Failure
        if: always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled'))
        run: echo "Failure"

      - name: Slack Notify Success
        if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
        run: echo "Success"
