name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check for changes
        id: check_changes
        run: echo "changes=true" >> "$GITHUB_OUTPUT"

      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: echo "Changes detected"
