name: Docker Image
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: fails
        if: always() && false
        run: echo "This is a failure"
      - name: succeeds
        if: always() && true
        run: echo "This is a success"
