name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  integration-tests:
    permissions:
      id-token: write # Important for at least docker gha cache
      contents: read

    name: "Run integration tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Build docker images
        # https://stackoverflow.com/a/74795460/6845813
        run: |
          env

          docker buildx bake --load --file docker-compose.yml --set *.cache-to="type=gha,mode=max" --set *.cache-from="type=gha"
