name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        test: [1, 2]

    steps:
      - run: echo "test_value=${{ matrix.test }}" >> $GITHUB_ENV
      - run: echo $test_value
      - run: echo ${{ env.test_value }}
