name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: "Print shell"
        shell: cmd
        run: |
          wmic datafile where Name="C:\Windows\system32\cmd.exe"
          ver
          uname -a
          env
          
