name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  integration-tests:
    permissions:
      id-token: write # Important for at least docker gha cache
      contents: read

    name: "Run integration tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker images
        # https://stackoverflow.com/a/74795460/6845813
        run: |
          export ACTIONS_CACHE_URL=$(echo "$ACTIONS_ID_TOKEN_REQUEST_URL" | grep -Po 'https://[^/]+/[^/]+/' | sed 's/pipelines/artifactcache/')
          export ACTIONS_RUNTIME_TOKEN=$ACTIONS_ID_TOKEN_REQUEST_TOKEN

          docker buildx build --load --file docker-compose.yml . --cache-to "type=gha,mode=max" --cache-from type=gha
