name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
        run: python -m pip install --upgrade pip         
        uses: Gr1N/setup-poetry@v8
        run: |
          poetry install

          python sotest/test.py
